Catch invalid commands

diff --git a/akulm b/akulm
--- a/akulm
+++ b/akulm
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+die() { printf '%s\n' "$*" >&2; exit 1; }
+
 do_copy() {
 	rsync -r \
 		"/usr/lib/modules/$(uname -r)/" \
@@ -36,4 +38,5 @@ case "${1}" in
 	gc)	 do_gc_links && do_gc_modules;;
 	link) do_link;;
   clean) do_clean;;
+  *) die "Invalid command: '${1}'. Valid commands: copy gc link clean";;
 esac
